### ISSUE TITLE
available_primary_key multiindex function

### ISSUE THREAD

**Issue by poplexity** [uuosio/rscdk#7]
Any reason there isn't an implementation similar to [CDT](https://github.com/AntelopeIO/cdt/blob/775d671e1e44f3a17a4eb406c93d498a6994026c/libraries/eosiolib/contracts/eosio/multi_index.hpp#L1366-L1383)?

**Comment by ghost** [comment]
Yes, you are right, rscdk is not fully compatible with CDT.

My recommendation is to use another table to read/write the current primary key.

Please check this example:
https://github.com/uuosio/rscdk/blob/main/examples/counter/lib.rs

**Comment by poplexity** [comment]
Yeah, that would work, my workaround was to query the end of the table and +1 it's primary key or use 1 if the table is empty, similar to how CDT did it.

If I find time I'll try to make a PR to add similar functionality to rscdk.
